# Configuration: https://github.com/zjedi/hugo-scroll/blob/master/exampleSite/config.toml


baseURL = 'https://zerodaedal.us/'
languageCode = 'en-us'
title = 'Zero Daedalus • Website Design & Consulting Services'
disableKinds = ["section", "taxonomy", "term", "RSS"]
clearDestinationDir = true
theme = 'hugo-scroll'
enableGitInfo = true

[params]
	description = "Zero Daedalus (ZeroDae for short) is a web consulting agency based in the Bay Area since 2012. We specialize in helping small businesses leverage the web to connect with customers and evolve the way they do business."
	copyright = "© Zero Daedalus 2024"
	images = ["https://cdn.zerodaedal.us/Logo_Full.png"]
	# title_guard = true

[params.meta]
	keywords = "web design,web development, web agency, web consulting, Bay Area, Silicon Valley"

    [[params.contacts]]
        label = "phone"
        value = "(209) 740 9063"
        url = "tel:12097409063"
        icon = "fa fa-phone"

    [[params.contacts]]
        label = "email"
        value = "captain@zerodaedalus.net"
        url = "mailto:captain@zerodaedalus.net"
        icon = "fa fa-envelope"